### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Tidinho90** [VMagnify/VMagnify#2]
Creation of the logo of the project

**Comment by scorpion905** [comment]
<img width="432" alt="VMagnifyLogo40" src="https://user-images.githubusercontent.com/96887077/153277875-669aff98-7872-4ea1-93a2-9036ae26aefe.png">
[VMagnify Logo.zip](https://github.com/VMagnify/VMagnify/files/8035725/VMagnify.Logo.zip)

**Comment by Tidinho90** [comment]
Can you commit the logo, @scorpion905 ?

**Comment by scorpion905** [comment]
> Can you commit the logo, @scorpion905 ?

I commited the logo under /static/img/logo, hope it's okay!

**Comment by Tidinho90** [comment]
It is okay and we can move it esaily if needed.
